#!/bin/bash

# Before running install
#
# mkdir /var/www/stl
# a2mod cgi


STLPATH=/var/www/stl
CGIPATH=/usr/lib/cgi-bin
WWWPATH=/var/www/html


mkdir -p $STLPATH
mkdir -p $CGIPATH
mkdir -p $WWWPATH

# copy stls
cp Tazzina.stl $STLPATH
cp Flower.stl $STLPATH
cp logo.stl $STLPATH
cp cubotest.stl $STLPATH

# copy CGIs
cp genstl.cgi $CGIPATH
cp gen.cgi $CGIPATH
cp Letters.dxf $CGIPATH
cp Write.scad $CGIPATH


# copy WWWs
cp form_test.html $WWWPATH
cp generatore.html $WWWPATH

